version: 2
updates:
  - package-ecosystem: "npm" # or pip, maven, gradle, docker, etc.
    directory: "/"          # location of package.json or requirements.txt
    schedule:
      interval: "daily"    # daily, weekly, monthly
    open-pull-requests-limit: 5
    target-branch: "main"